name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sh ./.github/workflows/configure.sh
    - name: Build binaries for Linux
      run: make release
    - name: Upload Linux binaries
      run: sh ./.github/workflows/upload.sh linux
    - name: Build binaries for macOS
      run: make clean && make release CC="zig cc -target arm64-macos"
    - name: Upload macOS binaries
      run: sh ./.github/workflows/upload.sh macos
