name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sh ./.github/workflows/configure.sh
    - name: Build binaries for Linux
      run: make release
    - name: Archive Linux binaries
      run: sh ./.github/workflows/make-archives.sh linux
    - name: Build binaries for macOS
      run: make clean && make release CC="zig cc -target aarch64-macos" TARMAN_OS=darwin
    - name: Archive macOS binaries
      run: sh ./.github/workflows/make-archives.sh macos
    - name: Upload all
      run: sh ./.github/workflows/upload.sh
